config/routes.rb
# This file is part of URM Usability Reporting Manager
# Copyright (C) 2012 internettechnik 
# Licensed under the GNU GPLv3 (http://www.gnu.org/licenses/gpl.txt) license.


URM::Application.routes.draw do
  
  resources :projects 
  resources :reports do
      collection do 
        get "ajax_add"
      end 
      member do
        get 'ajax_remove'
      end
  end
  # ajaxified methods new, update and destroy in the controller!
  resources :authors, 
        :persons, 
        :attributes_of_people, 
        :devices,
        :tasks, 
        :task_results,
        :questions,
        :answers,
        :interviews,
        :qandas,
        :findings,
        :documents,
        :videos,
        :transcript_events,
        :heuristics

  # TODO: use AJAX to manage (add/modify/remove)
  resources :eventcodes, :custom_attributes
  
  
  # user / admins / todo
  resources :todos
  
  # for authlogic sessions and users to login:
  resources :user_sessions
	match 'login' => "user_sessions#new",      :as => :login
	match 'logout' => "user_sessions#destroy", :as => :logout
  
  # give us our some normal resource routes for users
  resources :users  
  # a convenience route
  resource :user, :as => 'account', :only => [:show, :edit]  
  
  match 'signup' => 'users#new', :as => :signup
  
  
  # 2012-03-22 for url in registration mail
  match '/confirmation/:confirmation_code', :to => 'users#confirm', :as => :confirmation, :via => ["get","post"]
  
  
  resources :password_reset_request, :except => [:index, :show, :destroy]		
  
  
  root :to => "projects#index"
  
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer(4)      not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

# This file is part of URM Usability Reporting Manager
# Copyright (C) 2012 internettechnik 
# Licensed under the GNU GPLv3 (http://www.gnu.org/licenses/gpl.txt) license.

class Project < ActiveRecord::Base
  validates_presence_of :title 
  has_many :reports, :dependent => :destroy
  belongs_to :users
  belongs_to :roles

 	def summary
      self.title.to_s.truncate(15)+": "+self.description.to_s.truncate(25)
  end

end

app/controllers/projects_controller.rb
# This file is part of URM Usability Reporting Manager
# Copyright (C) 2012 internettechnik 
# Licensed under the GNU GPLv3 (http://www.gnu.org/licenses/gpl.txt) license.


class ProjectsController < ApplicationController
  load_and_authorize_resource
  # Note: this is set to "site home" (see routes.rb)
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml #{ render :xml => @projects }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    # TODO caching!!
    @Eventcodes = Eventcode.all
    @persontypes = Persontype.all
    @CustomAttribs = CustomAttribute.all
    
    @project = Project.new
    @project.title="Enter name"
    @project.save
    # should we create default entries with a project?? NO!!
    1.times do
    #  report = @project.reports.build
    #  1.times { report.authors.build }
    #  1.times { report.persons.build } 
    #  1.times { report.interviews.build } 
    #  interview = report.interviews.build
    #  1.times { interview.qandas.build }
    end
    respond_to do |format|
      format.html { render 'edit' }
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    # TODO caching!!
    @Eventcodes = Eventcode.all
    @persontypes = Persontype.all
    @CustomAttribs = CustomAttribute.all
    
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project.user = current_user
    # TODO caching!!
    @Eventcodes = Eventcode.all
    @persontypes = Persontype.all
    @CustomAttribs = CustomAttribute.all

    @project = Project.new(params[:project])
    respond_to do |format|
      if @project.save
        format.html { render  :action => "edit",
                              :notice => 'Project was successfully created.' }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
       # format.js
      else
        format.html { render  :action => "new", 
                              :notice => 'Fill in all required field before saving the project.' }
        format.xml  { render  :xml => @project.errors, :status => :unprocessable_entity }
       # format.js
      end
    end
  end


  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
    end
  end
  
  # todo: check what's that?
  def toggle_div 
     puts("is this code ever envoked??")    
     render(:update) { |page| page.toggle('toggle_div') }
  end


  # GET /projects/1.xml
  def show
    #TODO: cache!
    @Eventcodes = Eventcode.all 
    @project = Project.find(params[:id])

    # optionally we add the stylesheet instruction:
    # http://localhost:3000/projects/1.xml?includestyle=true
    @includestyle=params[:includestyle] || false

    respond_to do |format|
      format.xml  # use the custom show.xml.builder
    end
  end




  # AJAX-call
  def update
      @project = Project.find(params[:id])

      logger.debug("Ajax-save current project #{@project.summary }")
      @project.update_attributes(params[:project])
      flash[:notice] = "Updated project '"+@project.summary+"'"
      respond_to do | format |  
        format.js {
          render(:ajaxupdate, :locals=>{:project=>@project}) 
        }  
      end
  end


end

app/views/projects/_project.html.erb
<!-- SECTION SINGLE Project -->
<div id="project_<%=@project.id%>" class="border_project">

	<!-- SECTION SINGLE Project Summary (modifiable details) -->
	<div class="toggle_project">
			<%= form_for( @project, 
					:remote => true, 
					:html => {:class => "edit_project_#{@project.id}"}	
					) do |frm_pro| %>
				<%= link_to_function(t(:'.section_title'), 
					toggler("#toggle_",@project),
					:title => t(:'.hint_section_title') ) %>
				<%= frm_pro.text_field(	:title, 
					:placeholder => t(:'.placeholder_title'), 
					:title => t(:'.hint_title'),
					:class => 'submittable') %>
				<%= link_to( image_tag('delete.png'),
					project_path(@project),
					# Note: we redirect to overview page, so NO AJAX here!!
					:method => :delete, :remote		=> false,
					:confirm => t(:'.delete_confirm',:summary => @project.summary),
					:title => t(:'.delete_hint',	:summary => @project.summary) )	%>
					 
				&nbsp;&nbsp;&nbsp;	
				<%= link_to(image_tag('xml.png') , 	project_path(@project, 	:format => :xml),
				  						:title => t(:'projects.hint_export') )%>
				&nbsp;&nbsp;&nbsp;
			 	<%= link_to(image_tag('preview.png'), 	project_path(@project, 	:includestyle=>true, 
														:format => :xml),
										:title => t(:'projects.hint_view'))  %>
			<% end  %> <!-- end of project-form -->
			
			<!-- SUB SECTION SINGLE Project Details (modifiable details) -->
			<div id="toggle_project_<%=@project.id %>">
				<!-- SECTION PROJECT (modifiable details) -->
				<%= form_for(@project, 
					:remote => true, 
					:html => {:class => "edit_project_#{@project.id}"}
					) do |frm_pro| %>
					<table id="table_project">	  
						<tr><th class="leftcolumn"></th><!-- left column fixed width with css --></tr>
						<tr>
							<td><%= frm_pro.label(:description, 
									t(:'.description'),
									:title => t(:'.hint_description') ) %></td>
							<td><%= frm_pro.text_area :description, 
									:rows => 4,
							 		:placeholder => t(:'.placeholder_description'),
							 		:title => t(:'.hint_description'),
									:class => 'submittable'	%></td>
						</tr>
					</table>  
				<% end # end of project-form %>

				<div id="project_message_<%=@project.id%>" class="ajax_message"></div>
		
				<!-- SECTION ALL REPORTS -->
				<div class="border_reports">
					<div class="toggle_all_reports">
						<%= link_to_function( t(:'reports.section_title'),
								toggler("#toggle_all_reports_of_",@project),
								:title => t(:'reports.toggle_section_title')
							) %>
						<span id="summary_reports"><%= allreports_summary(@project) %></span>	
						<div id="toggle_all_reports_of_project_<%=@project.id%>">
					 		<%= render :partial =>'reports/report', 
								:collection => @project.reports,
								:locals => {:allreports => @project.reports}
							%>  
						</div> <!-- end all reports-->
					</div><!-- end toggle for all reports-->
				</div><!-- end border all reports-->
					
				<!-- html for new report will be inserted here -->
				<div id="new_report_for_project"></div>
				
				<%= link_to( image_tag('add.png')+t(:'.add_ta_link'),
						ajax_add_reports_path(:project_id => @project.id, :testtype => 'ta'),
						:remote		=> true,
						:title => t(:'.add_ta_link')) %>
				
				<%= link_to( image_tag('add.png')+t(:'.add_he_link'),
						ajax_add_reports_path(:project_id => @project.id, :testtype => 'he'),
						:remote		=> true,
						:title => t(:'.add_he_link')) %>
				
			</div><!-- end of id toggle_project (details)-->
		</div> <!-- end of class toggle (project with summary)-->
</div> <!-- end of single project -->

<br />

<%= link_to t(:'back'),  projects_path, :title => t(:'hint_back') %>

app/views/projects/ajaxupdate.js.erb
showToast("<%= escape_javascript( t(:'.updated', :summary => @project.summary) ) %>");
resetHighlightingForElems('.edit_project_<%=@project.id%>');

app/views/projects/edit.html.erb
<%#
Note the structure for nesting the html-div elements

e.g.:
...
 <!-- SECTION ALL REPORTS -->
 render collection
	<!-- SECTION SINGLE REPORT -->
	<div id="report_777" class="border_reports">
		<!-- SECTION SINGLE REPORT Summary (modifiable details) -->
		<div class="toggle"> (OPTIONAL - if identation needed)
			form for report (header)
			<!-- SUB SECTION SINGLE REPORT Details (modifiable details) -->
			<div id="toggle_report_77">
				form for report (details)
					<table id="table_report">
				<div id="report_message_77" class="ajax_message"></div>
				<!-- SECTION ALL AUTHORS -->
					render collection
						...
				<!-- html for new author of this report will be inserted here -->
				<div id="new_author_for_report_7"></div>
				<%= link_to( image_tag('add.png'),...
				
 div 'new_report_for_project' and link for: "add/new"
...

%>
<%= render('projects/project') %>

app/views/projects/index.html.erb
<h1><%= t '.manage_projects' %></h1>

<table class="table_index">
	<tr>
		<th><%= t '.project_tab_title' %></th>
		<th><%= t '.project_descripion_tab_title' %></th>
		<th><%=t(:'.project_manage_tab_title')%></th>
	</tr>

	<% @projects.each do |project| %>
		<tr>
		  	<td><%= link_to( project.title, edit_project_path(project),
				:title => t(:'projects.hint_edit') 
				) %>
				&nbsp;&nbsp;&nbsp;
				<%= link_to(image_tag('edit.png'), edit_project_path(project),
					:title => t(:'projects.hint_edit') ) %>
			</td>
		  <td><%= project.description %>
		<ul>
			<% project.reports.each do |r| %>
				<li>
					<%= link_to(r.title , 	edit_report_path(r), 
											:title => t(:'reports.hint_edit') ) %>
					&nbsp;&nbsp;&nbsp;
					<%= link_to(image_tag('edit.png'), 	edit_report_path(r), 
											:title => t(:'reports.hint_edit') ) %>
					&nbsp;&nbsp;&nbsp;	
					<%= link_to(image_tag('xml.png') , 	report_path(r, 	:format => :xml),
					  						:title => t(:'reports.hint_export') )%> 
					&nbsp;&nbsp;&nbsp;	
					<%= link_to(image_tag('preview.png'), 	report_path(r, 	:includestyle=>true, 
															:format => :xml),
											:title => t(:'reports.hint_view'))  %>
					&nbsp;&nbsp;&nbsp;	
					<%= link_to(image_tag('zip.png'), 	report_path(r, 
											 :format => :xml,
											 :includestyle => true,
											 :zip => true),
											:title => t(:'reports.hint_zip'))  %>
				<br /> <%=r.description %>	<br /><br />
				</li>
			<% end %>
		</ul>
		</td>
		  <td>
				<%= link_to(image_tag('xml.png') , 	project_path(project, 	:format => :xml),
				  						:title => t(:'projects.hint_export') )%>
				&nbsp;&nbsp;&nbsp;	
				<%= link_to(image_tag('preview.png'), 	project_path(project, 	:includestyle=>true, 
														:format => :xml),
										:title => t(:'projects.hint_view'))  %>
</td>
		</tr>
	<% end %>
</table>

<br />
<%= link_to( image_tag('add.png')+t(:'.add_link'),
		 new_project_path, 
		:title => t(:'.add_hint')
	) %>